"use strict";

// UI strings for the visual Settings window. Looked up in the main process
// (window title) and shipped to the page over IPC, so the renderer never
// needs Node access.

const en = {
  title: "Opensource ToDo Settings",
  tabGeneral: "General",
  tabAppearance: "Appearance",
  tabShortcuts: "Shortcuts",

  sectionStartup: "Startup",
  sectionWindow: "Window",
  sectionUpdates: "Updates",
  sectionTheme: "Theme",
  sectionCustomTheme: "Custom theme colors",

  alwaysOnTop: "Always on top",
  autoLaunch: "Launch at login",
  launchMinimized: "Launch minimized",
  hideTray: "Hide tray icon",
  requestExitConfirmation: "Confirm before quitting",
  reopenLastList: "Reopen last list on launch",
  useGlobalShortcuts: "Global shortcut keys",
  disableAutoUpdateCheck: "Don't check for updates automatically",
  updateCheckPeriod: "Check for updates every",
  hours: "{n} hours",

  menuBarHidden: "Hide menu bar",
  menuBarHiddenHint: "Press Alt to show it temporarily",
  autoNightMode: "Follow system theme",
  autoNightModeHint: "Match the system light or dark appearance",
  listAccents: "Follow list colors",
  language: "Language",
  "language.system": "System",
  "language.en": "English",
  "language.ru": "Русский",
  invertNewTaskPosition: "New tasks at the bottom",
  customMode: "Custom theme",
  customModeHint: "Use the colors below instead of To-Do's theme",
  customThemeHint: "Colors are read from todo.json when Opensource ToDo starts; changes take effect after restart. Values with transparency keep their alpha.",
  defaultValue: "Default: {value}",
  resetTheme: "Reset custom theme to defaults",
  confirmResetTheme: "Reset all custom theme colors to their defaults?",

  shortcutsHint: "Accelerators use Electron syntax, e.g. Ctrl+Shift+T or CmdOrCtrl+Alt+A. Changes take effect after restart.",
  command: "Command",
  shortcut: "Shortcut",
  invalidShortcut: "A shortcut cannot be empty",

  openJson: "Open todo.json in editor",
  openFolder: "Open config folder",
  close: "Close",
  configPath: "Config file",

  saved: "Saved",
  restartNote: "Takes effect after Opensource ToDo restarts",
  menuNote: "Checkboxes in the application menu catch up after restart.",
  errorSave: "Could not save: {message}",
  errorLoad: "Could not load settings: {message}",

  commands: {
    "add-due-date": "Add due date",
    "set-reminder": "Set reminder",
    "set-repeat": "Set repeat",
    "add-my-day": "Add to My Day",
    "complete-todo": "Complete task",
    "delete-list": "Delete list",
    "delete-todo": "Delete task",
    "global-create-todo": "New task (global)",
    "global-search-todo": "Search (global)",
    "global-toggle-window": "Show/hide window (global)",
    "hide-todo": "Hide To-Do",
    important: "Important",
    "my-day": "My Day",
    "new-list": "New list",
    "new-todo": "New task",
    planned: "Planned",
    "rename-list": "Rename list",
    "rename-todo": "Rename task",
    return: "Back / Escape",
    settings: "To-Do settings",
    "sign-out": "Sign out",
    tasks: "Tasks",
    "toggle-dark-mode": "Toggle dark theme",
    "toggle-custom-mode": "Toggle custom theme",
    "toggle-sidebar": "Toggle sidebar",
    exit: "Quit Opensource ToDo",
  },

  // Building blocks for humanised theme keys: bgPrimary → "Background primary"
  themeWords: {
    bg: "Background",
    fontColor: "Font color",
    primary: "primary",
    secondary: "secondary",
    tertiary: "tertiary",
    transparent: "transparent",
    hover: "hover",
    active: "active",
    separator: "separator",
    border: "border",
    scrollbar: "scrollbar",
    warning: "warning",
    brand: "brand",
    danger: "danger",
    disable: "disabled",
    red: "Red",
    blue: "Blue",
    skyblue: "Sky blue",
    purple: "Purple",
    green: "Green",
  },
};

const ru = {
  title: "Настройки Opensource ToDo",
  tabGeneral: "Основные",
  tabAppearance: "Внешний вид",
  tabShortcuts: "Горячие клавиши",

  sectionStartup: "Запуск",
  sectionWindow: "Окно",
  sectionUpdates: "Обновления",
  sectionTheme: "Тема",
  sectionCustomTheme: "Цвета пользовательской темы",

  alwaysOnTop: "Поверх других окон",
  autoLaunch: "Запускать при входе в систему",
  launchMinimized: "Запускать свёрнутым",
  hideTray: "Скрывать значок в трее",
  requestExitConfirmation: "Подтверждать выход",
  reopenLastList: "Открывать последний список",
  useGlobalShortcuts: "Глобальные горячие клавиши",
  disableAutoUpdateCheck: "Не проверять обновления автоматически",
  updateCheckPeriod: "Проверять обновления каждые",
  hours: "{n} ч",

  menuBarHidden: "Скрыть строку меню",
  menuBarHiddenHint: "Нажмите Alt, чтобы показать её временно",
  autoNightMode: "Следовать теме системы",
  autoNightModeHint: "Светлое или тёмное оформление как в системе",
  listAccents: "Следовать цветам списков",
  language: "Язык",
  "language.system": "Как в системе",
  "language.en": "English",
  "language.ru": "Русский",
  invertNewTaskPosition: "Новые задачи снизу",
  customMode: "Пользовательская тема",
  customModeHint: "Использовать цвета ниже вместо темы To-Do",
  customThemeHint: "Цвета читаются из todo.json при запуске Opensource ToDo; изменения вступят в силу после перезапуска. Полупрозрачные значения сохраняют прозрачность.",
  defaultValue: "По умолчанию: {value}",
  resetTheme: "Сбросить цвета темы",
  confirmResetTheme: "Сбросить все цвета пользовательской темы к значениям по умолчанию?",

  shortcutsHint: "Сочетания в формате Electron, например Ctrl+Shift+T или CmdOrCtrl+Alt+A. Изменения вступят в силу после перезапуска.",
  command: "Команда",
  shortcut: "Сочетание",
  invalidShortcut: "Сочетание не может быть пустым",

  openJson: "Открыть todo.json в редакторе",
  openFolder: "Открыть папку с настройками",
  close: "Закрыть",
  configPath: "Файл настроек",

  saved: "Сохранено",
  restartNote: "Вступит в силу после перезапуска Opensource ToDo",
  menuNote: "Галочки в меню приложения обновятся после перезапуска.",
  errorSave: "Не удалось сохранить: {message}",
  errorLoad: "Не удалось загрузить настройки: {message}",

  commands: {
    "add-due-date": "Добавить срок",
    "set-reminder": "Напоминание",
    "set-repeat": "Повтор",
    "add-my-day": "Добавить в «Мой день»",
    "complete-todo": "Завершить задачу",
    "delete-list": "Удалить список",
    "delete-todo": "Удалить задачу",
    "global-create-todo": "Новая задача (глобально)",
    "global-search-todo": "Поиск (глобально)",
    "global-toggle-window": "Показать/скрыть окно (глобально)",
    "hide-todo": "Скрыть To-Do",
    important: "Важно",
    "my-day": "Мой день",
    "new-list": "Новый список",
    "new-todo": "Новая задача",
    planned: "Запланировано",
    "rename-list": "Переименовать список",
    "rename-todo": "Переименовать задачу",
    return: "Назад / Escape",
    settings: "Настройки To-Do",
    "sign-out": "Выйти из аккаунта",
    tasks: "Задачи",
    "toggle-dark-mode": "Переключить тёмную тему",
    "toggle-custom-mode": "Переключить пользовательскую тему",
    "toggle-sidebar": "Показать/скрыть боковую панель",
    exit: "Выйти из Opensource ToDo",
  },

  themeWords: {
    bg: "Фон",
    fontColor: "Цвет текста",
    primary: "основной",
    secondary: "дополнительный",
    tertiary: "третичный",
    transparent: "прозрачный",
    hover: "при наведении",
    active: "активный",
    separator: "разделитель",
    border: "граница",
    scrollbar: "полоса прокрутки",
    warning: "предупреждение",
    brand: "фирменный",
    danger: "опасность",
    disable: "неактивный",
    red: "Красный",
    blue: "Синий",
    skyblue: "Голубой",
    purple: "Фиолетовый",
    green: "Зелёный",
  },
};

const tables = { en, ru };

function get(lang) {
  return tables[lang] || en;
}

module.exports = { en, ru, get };
